{
 "title": "hw1",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FS free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 *\nnode_filesystem_avail_bytes{\n  mountpoint=\"/\",\n  fstype!~\"tmpfs|overlay|squashfs\"\n}\n/\nnode_filesystem_size_bytes{\n  mountpoint=\"/\",\n  fstype!~\"tmpfs|overlay|squashfs\"\n}"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay|squashfs\"}"
    }
   ]
  },
  {
   "title": "free RAM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes (IEC)" } },
   "yaxes": [
    { "format": "bytes (IEC)" }
   ],
   "targets": [
    { "expr": "node_memory_MemAvailable_bytes" }
   ]
  },
  {
   "title": "CPU Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short / none" } },
   "yaxes": [
    { "format": "short / none" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}"
    },
    {
     "expr": "node_load5\n/\ncount without (cpu, mode) (node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"})"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[5m])) * 100)"
    }
   ]
  }
 ]
}